INSERT INTO school (school_name, postal_code, city, phone, email, principal_name, operator_name)
VALUES ('Example School', '12345', 'New York', '1234567890', 'example@email.com', 'John Smith', 'Jane Doe'),
       ('Example School2', '12342', 'New York2', '1234567892', 'example@email.com2', 'John Smith2', 'Jane Doe2'),
       ('Example School3', '12343', 'New York3', '1234567893', 'example@email.com3', 'John Smith3', 'Jane Doe3');

INSERT INTO operator (first_name, last_name, age, postal_code, email, gender) 
VALUES ('Dierdre', 'Millett', 33, 15151, 'dmillett0@latimes.com', 'Agender'),
       ('Miller', 'Maunton', 64, 23421, 'mmaunton1@cpanel.net', 'Male'),
       ('Emmy', 'Klima', 27, 54231, 'eklima2@theguardian.com', 'Female');

INSERT INTO BOOK (ISBN, publisher, title, writer, num_of_pages, category)
VALUES  ('103997371-X', 'HarperCollins', 'Pride and Prejudice', 'Berton Sparwell', 224, 'Comedy|Drama|Musical'),
        ('953637791-8', 'Macmillan Publishers', 'Animal Farm', 'Farly Cutten', 1169, 'Action|Crime|Drama'),
        ('514898620-4', 'Penguin Random House', 'The Catcher in the Rye', 'Adina Mansion', 1392, 'Comedy|Horror'),
        ('644989747-3', 'HarperCollins', 'The Catcher in the Rye', 'Jolie Geram', 573, 'Western'),
        ('509749099-1', 'HarperCollins', 'Pride and Prejudice', 'Laurent Hepher', 102, 'Comedy|Romance'),
        ('033443326-6', 'Simon & Schuster', 'Brave New World', 'Vinnie Frostdick', 735, 'Documentary'),
        ('395901653-0', 'Scholastic Corporation', 'Animal Farm', 'Anstice Fearnside', 758, 'Drama'),
        ('191001945-3', 'HarperCollins', 'The Great Gatsby', 'Janot De Andreis', 1377, 'Crime|Drama|Mystery'),
        ('893833598-4', 'Pearson Education', '1984', 'Cherlyn Andriveau', 579, 'Drama|Mystery|Romance'),
        ('150286996-9', 'Macmillan Publishers', 'Pride and Prejudice', 'Dannie Cothey', 335, 'Crime|Mystery|Thriller'),
        ('972882412-2', 'Simon & Schuster', 'Animal Farm', 'Clayton Targe', 56, 'Documentary'),
        ('994124758-7', 'Scholastic Corporation', 'Pride and Prejudice', 'Shayna Astbery', 779, 'Horror'),
        ('410762699-7', 'Macmillan Publishers', 'The Catcher in the Rye', 'Graeme Wank', 565, 'Comedy'),
        ('038024820-4', 'Scholastic Corporation', 'Lord of the Flies', 'Kore Chimenti', 550, 'Crime|Mystery'),
        ('420137896-9', 'Macmillan Publishers', 'Animal Farm', 'Nani Squibb', 317, 'Drama'),
        ('559405846-X', 'Hachette Book Group', 'Pride and Prejudice', 'Guntar Ollivierre', 718, 'Action|Fantasy'),
        ('823249275-9', 'Pearson Education', 'Animal Farm', 'Danya Piele', 539, 'Mystery|Thriller'),
        ('520395435-6', 'Penguin Random House', 'The Lord of the Rings', 'Alvera Cartmell', 1281, 'Action|Adventure|Drama|Thriller|War'),
        ('288441694-3', 'Simon & Schuster', 'To Kill a Mockingbird', 'Rorie Ethridge', 127, 'Comedy'),
        ('801958873-6', 'Pearson Education', 'Pride and Prejudice', 'Jereme Swinnerton', 1036, 'Action|Sci-Fi'),
        ('975084101-8', 'Scholastic Corporation', 'The Lord of the Rings', 'Torrence Aspin', 1422, 'Adventure|Comedy|Drama'),
        ('820723934-4', 'HarperCollins', 'Lord of the Flies', 'Buddie McAvinchey', 1273, 'Drama|Fantasy|Romance'),
        ('500767606-3', 'Simon & Schuster', 'The Great Gatsby', 'Goldy McKimmie', 1461, 'Action|Crime|Mystery|Romance|Thriller'),
        ('279203269-3', 'Hachette Book Group', 'Animal Farm', 'Sauveur Whardley', 711, 'Drama'),
        ('465435301-1', 'Macmillan Publishers', 'To Kill a Mockingbird', 'Darya Tompkinson', 819, 'Action'),
        ('707443909-6', 'Pearson Education', 'To Kill a Mockingbird', 'Gregoor Sidebottom', 886, 'Drama|Thriller'),
        ('333670838-9', 'Pearson Education', 'Animal Farm', 'Curr Idenden', 219, 'Drama|Fantasy|Horror|Thriller'),
        ('394214192-2', 'Bloomsbury Publishing', 'The Catcher in the Rye', 'Ros Mateja', 1221, 'Horror|Mystery|Thriller'),
        ('294182365-4', 'HarperCollins', 'Brave New World', 'Costa Kenderdine', 1194, 'Comedy|Horror'),
        ('184858187-4', 'Bloomsbury Publishing', 'The Catcher in the Rye', 'Tomaso Tollady', 444, 'Drama');

INSERT INTO library_user (username, user_password, user_name, user_surname, user_email, user_age, user_sex, user_class) 
VALUES  ('Karlie', 'Boltwood', 'kboltwood0@youku.com', 11, 'Female', 2);
        ('groswarn0', 'jKz2cJ', 'Galvin', 'Roswarn', 'groswarn0@fotki.com', 14, 'Male', 6),
        ('gmars1', 'F4E6Laij', 'Giselle', 'Mars', 'gmars1@cyberchimps.com', 16, 'Female', 11),
        ('bdelias2', 'jVw9TtT', 'Baryram', 'D''Elias', 'bdelias2@hp.com', 13, 'Male', 2),
        ('lblampy3', 'AT27tnTar', 'Leslie', 'Blampy', 'lblampy3@cmu.edu', 11, 'Female', 4),
        ('joronan4', 'm9LdYwwJ', 'Jarrod', 'O'' Ronan', 'joronan4@nps.gov', 12, 'Male', 6),
        ('wbollard5', '5aSC2ksi8d', 'Wang', 'Bollard', 'wbollard5@chron.com', 9, 'Male', 10),
        ('gjaegar6', 'UEBUqxNd1Tkk', 'Gwendolyn', 'Jaegar', 'gjaegar6@europa.eu', 12, 'Female', 7),
        ('nstark7', 'LHcD07sqL', 'Nathanial', 'Stark', 'nstark7@ed.gov', 7, 'Male', 10),
        ('gburgott8', '2HEz0TLO4w5Z', 'Guss', 'Burgott', 'gburgott8@imgur.com', 17, 'Male', 7),
        ('csyce9', 'k7J5rJn', 'Charyl', 'Syce', 'csyce9@jalbum.net', 10, 'Female', 2),
        ('mmiddasa', 'CNJxX0', 'Margeaux', 'Middas', 'mmiddasa@go.com', 9, 'Female', 4),
        ('hdantuonib', 'NXXr63U', 'Hanan', 'D''Antuoni', 'hdantuonib@sohu.com', 9, 'Male', 1),
        ('alepruvostc', 'B8hTdTjVn', 'Anna-diana', 'Le Pruvost', 'alepruvostc@google.com.hk', 14, 'Female', 9),
        ('tvickerstaffd', 'cOcgjDEKa5', 'Trueman', 'Vickerstaff', 'tvickerstaffd@soundcloud.com', 12, 'Male', 10),
        ('mferreiroe', 'cqg1DheGJ', 'Moria', 'Ferreiro', 'mferreiroe@ameblo.jp', 10, 'Female', 7),
        ('bcarhartf', 'HFj8fNa', 'Beryl', 'Carhart', 'bcarhartf@nydailynews.com', 14, 'Female', 4),
        ('adivallg', 'zoGCVp', 'Aurea', 'Divall', 'adivallg@cornell.edu', 9, 'Female', 12),
        ('ycocheth', '3IeK0Q', 'Yankee', 'Cochet', 'ycocheth@list-manage.com', 8, 'Male', 3),
        ('jwilderi', '9GHfoZyUiXDP', 'Jard', 'Wilder', 'jwilderi@yellowbook.com', 12, 'Male', 8),
        ('mconsadinej', 'p009fuyeQqaM', 'Martguerita', 'Consadine', 'mconsadinej@timesonline.co.uk', 13, 'Female', 1),
        ('jyoudek', 'IFkWgRsiox', 'Jacqueline', 'Youde', 'jyoudek@smugmug.com', 17, 'Female', 12),
        ('rmingayl', 'VWDXjI', 'Russell', 'Mingay', 'rmingayl@mail.ru', 11, 'Male', 6),
        ('fdipietrom', 'WAnTJo2PXQh', 'Fran', 'Di Pietro', 'fdipietrom@privacy.gov.au', 14, 'Male', 2),
        ('ressonn', 'WYhxV5kwHg5', 'Reginauld', 'Esson', 'ressonn@ibm.com', 15, 'Male', 10),
        ('dspallso', 'rcFhXtcJhUjc', 'Darrell', 'Spalls', 'dspallso@blogs.com', 10, 'Male', 5),
        ('vrobbingsp', 'aPConWPP0Da', 'Vikky', 'Robbings', 'vrobbingsp@domainmarket.com', 13, 'Female', 2),
        ('jjaqueminetq', 'zrnG0y2q', 'Jarrad', 'Jaqueminet', 'jjaqueminetq@prnewswire.com', 15, 'Male', 7),
        ('acloneyr', 'JrFrdu', 'Allene', 'Cloney', 'acloneyr@icio.us', 7, 'Female', 2),
        ('ebrisards', 'M7exLXysBwqz', 'Eberto', 'Brisard', 'ebrisards@aol.com', 17, 'Male', 1),
        ('bbonallickt', 'kNABqd2', 'Bale', 'Bonallick', 'bbonallickt@wunderground.com', 14, 'Male', 11),
        ('dbaudu', 'R0V5D3', 'Delmar', 'Baud', 'dbaudu@com.com', 9, 'Male', 7),
        ('crichfieldv', 'vnUJgajZyN2t', 'Cecilius', 'Richfield', 'crichfieldv@plala.or.jp', 14, 'Male', 3),
        ('vstieblerw', 'BMa8gvNR16', 'Victor', 'Stiebler', 'vstieblerw@state.gov', 9, 'Male', 8),
        ('amcnivenx', 'c3ZAGS', 'Arnoldo', 'McNiven', 'amcnivenx@yale.edu', 17, 'Male', 9),
        ('phowelsy', 'oJ5Dtii6o', 'Patrizius', 'Howels', 'phowelsy@imageshack.us', 16, 'Male', 7),
        ('kcinnamondz', 'UbM867AG', 'Kenyon', 'Cinnamond', 'kcinnamondz@qq.com', 13, 'Male', 1),
        ('rhallgath10', 'daprWHJ92d3n', 'Rudy', 'Hallgath', 'rhallgath10@mashable.com', 9, 'Male', 2),
        ('gdugall11', 'zwkBnN', 'Gradey', 'Dugall', 'gdugall11@usa.gov', 8, 'Male', 5),
        ('cworsnup12', 'xA7SrThAy8', 'Camile', 'Worsnup', 'cworsnup12@economist.com', 18, 'Female', 6),
        ('esteane13', 'Yvkn0NtcFfN7', 'Emmerich', 'Steane', 'esteane13@gravatar.com', 7, 'Male', 2),
        ('ldecourtney14', 'QdBNZVcfAr', 'Loydie', 'De Courtney', 'ldecourtney14@instagram.com', 17, 'Male', 9),
        ('mkobel15', 'MY3jvN5Xp', 'Madelyn', 'Kobel', 'mkobel15@1688.com', 9, 'Female', 11),
        ('klangston16', 'c3UY3zl', 'Kimberlyn', 'Langston', 'klangston16@bloglines.com', 11, 'Female', 5),
        ('wmatzen17', 'BrgEYgMcO', 'Welby', 'Matzen', 'wmatzen17@usa.gov', 9, 'Male', 7),
        ('kiannazzi18', 'vQbkTvTCG5X', 'Kalie', 'Iannazzi', 'kiannazzi18@imgur.com', 9, 'Female', 11),
        ('rburth19', 'hP3sJIMJSjs0', 'Rickie', 'Burth', 'rburth19@apple.com', 12, 'Male', 8),
        ('tdyke1a', 'qyzRf7s', 'Tully', 'Dyke', 'tdyke1a@forbes.com', 8, 'Male', 9),
        ('rjackling1b', 'JXyUM6UhXNX1', 'Rinaldo', 'Jackling', 'rjackling1b@webnode.com', 7, 'Male', 11),
        ('jkiossel1c', 'djbrr3wkwouV', 'Joli', 'Kiossel', 'jkiossel1c@ucoz.ru', 9, 'Female', 12),
        ('slaxon1d', 'ix53NFtaJL2t', 'Syman', 'Laxon', 'slaxon1d@ebay.com', 8, 'Male', 7),
        ('mclackson0', 'FX1QZFPbg0GO', 'Marchall', 'Clackson', 'mclackson0@live.com', 47, 'Male', 10),
        ('rnajera1', 'cFjlWCXsh', 'Rosabelle', 'Najera', 'rnajera1@thetimes.co.uk', 51, 'Female', 11),
        ('aparks2', '8PqPbZXj9fH', 'Alan', 'Parks', 'aparks2@wikimedia.org', 62, 'Male', 5),
        ('tmeo3', 'xZkzO5525', 'Titus', 'Meo', 'tmeo3@wordpress.org', 26, 'Male', 11),
        ('bnussen4', 'nWcLn6YSC', 'Barde', 'Nussen', 'bnussen4@dailymotion.com', 57, 'Male', 10),
        ('msickamore5', 'KDD29p2A', 'Miller', 'Sickamore', 'msickamore5@indiatimes.com', 47, 'Male', 4),
        ('gstoggles6', 'RISenZ6cZ', 'Gaynor', 'Stoggles', 'gstoggles6@ucsd.edu', 59, 'Female', 7),
        ('amostyn7', 'Vc8IoGZQ', 'Anitra', 'Mostyn', 'amostyn7@opensource.org', 54, 'Female', 7),
        ('vkonrad8', 'mougbvoVcJud', 'Valerye', 'Konrad', 'vkonrad8@bbc.co.uk', 63, 'Female', 4),
        ('bconnue9', 'oJGn8hY', 'Brunhilde', 'Connue', 'bconnue9@4shared.com', 59, 'Female', 4);